name: main

on: 
  push:
    branches:
      - master
    tags:
      - "*"
        
jobs:
  build:
    runs-on: ubuntu-latest
  
    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
    
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
    
      - name: Publish
        run: | 
          mkdir release
          chmod 755 buildall.sh
          ./buildall.sh release
        
      - name: Create release
        if: ${{ github.event_name == 'push' && github.ref_type == 'tag' }}
        uses: softprops/action-gh-release@v1
        with:
          body: |
            - [更新日志](https://github.com/Harlan-H/M3u8Downloader_H.Plugins/blob/master/Changelog.md)
          draft: false
          prerelease: false
          files:  release/*.zip
              
